# name of the software
name: Angular Loading Overlay
# current version of the software
version: 0.3.0
# url of the download button
downloadUrl: https://github.com/bsalex/angular-loading-overlay
# licence of the software
license: Apache License
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/bsalex/angular-loading-overlay

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/bsalex/angular-loading-overlay
  - title: Issues
    url: https://github.com/bsalex/angular-loading-overlay/issues

# header
header:
  color1: "#080331"
  color2: "#bb6c6c"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: bsalex
  repo: angular-loading-overlay

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: https://twitter.com/bsalexmail

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', '*.iml']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
